services:
  api:
    build: .
    container_name: iuran-rt-api
    restart: unless-stopped
    ports:
      - "8002:8000"
    env_file:
      - ./.env
    networks:
      - iuran-rt-network

  web:
    build: ../iuran-rt-apps
    container_name: iuran-rt-web
    restart: unless-stopped
    ports:
      - "3003:80"
    depends_on:
      - api
    networks:
      - iuran-rt-network

networks:
  iuran-rt-network:
    driver: bridge
