services:
  api:
    build: .
    container_name: iuran-rt-api
    restart: unless-stopped
    ports:
      - "8002:8000"
    env_file:
      - ./.env
    command: node --watch index.js
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - iuran-rt-network

  web:
    build:
      context: ../iuran-rt-apps
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-}
    container_name: iuran-rt-web
    restart: unless-stopped
    ports:
      - "3003:80"
    depends_on:
      - api
    networks:
      - iuran-rt-network

networks:
  iuran-rt-network:
    driver: bridge
